### ISSUE TITLE
kube-rbac-proxy image update

### ISSUE THREAD

**Issue by nitrocb** [k3s-io/cluster-api-k3s#102]
Currently cluster-api uses a quite old kube-rbac-proxy container image version v0.5.0.
The newest kube-rbac-proxy image is v0.16.0.

Is something speaking against an update here? Our CVE scanners are already complaining :-)

The corresponding code is here I guess:

https://github.com/k3s-io/cluster-api-k3s/blob/286bede3a5d3d7a4372d37dfd8f5e34c55b76111/bootstrap/config/default/manager_auth_proxy_patch.yaml#L13

**Comment by nasusoba** [comment]
It is not maintained for a while, will bump up the version, thanks!
