### ISSUE TITLE
CAPD support

### ISSUE THREAD

**Issue by zawachte** [k3s-io/cluster-api-k3s#36]

**Comment by nasusoba** [comment]
Hi @zawachte, I am trying out CAPI-k3s with CAPD. I tried to follow @richardcase's [WIP commit note](https://github.com/k3s-io/cluster-api-k3s/pull/93) (there is some CAPD related things), but it seems that it gets stuck when bootstrapping the docker node. How is the current status for supporting CAPD?

**Comment by zawachte** [comment]
Well that is awesome. Thanks! Can't wait to give this a spin.
