### ISSUE TITLE
Scale down control plane not working (2 CP to 1 CP)

### ISSUE THREAD

**Issue by nasusoba** [k3s-io/cluster-api-k3s#96]
Create a cluster with 3 control plane and then scale down to 1 is buggy, need more investigation.

**Comment by mogliang** [comment]
Wonderful! @nasusoba 
So we've begin to gain from e2e test!

**Comment by nasusoba** [comment]
Seems that after adding `etcd.k3s.cattle.io/remove="true"` annotation to the node before deleting the `Machine`, the scaling down of CP could be completed. refer to [[master] Add `etcd-member-management` controller to K3s by Oats87 · Pull Request #4001 · k3s-io/k3s (github.com)](https://github.com/k3s-io/k3s/pull/4001)

But the node drain is never finished (the machine will be forced to deleted after 10min). Need more investigation on why draining is failed, and if adding the annotation is the official way to remove a node.
